# window.reload();
# Fonction Compteur qui appele la fonction ActualiserCompteur() toutes les secondes

Compteur = ->
  setInterval 'ActualiserCompteur()', 1000
  return

# Fonction qui appele une fonction toutes les secondes
#Compteur

ActualiserCompteur = ->
  $seconde++
  if $seconde == 60
    $seconde = 0
    $minute++
  if $minute == 60
    $seconde = 0
    $minute = 0
    $heure++
  if $heure == 24
    $seconde = 0
    $minute = 0
    $heure = 0
    $jour++
  if $heure < 10
    $text = '0' + $heure + ' : '
  else
    $text = $heure + ' : '
  if $minute < 10
    $text += '0' + $minute + ' : '
  else
    $text += $minute + ' : '
  if $seconde < 10
    $text += '0' + $seconde
  else
    $text += $seconde
  $('#Compteur').val $text
  # $("#CompteurJour").val($jour);
  return

$seconde = 0
$minute = 0
$heure = 0
$jour = 0
d = new Date
interupt = false
Compteur()

# ---
# generated by js2coffee 2.0.4